import json
import os

KEY_IMAGES = [
    "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop", # Key 1
    "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=600&auto=format&fit=crop", # Key 2
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop", # Key 3
    "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop", # Key 4
    "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=600&auto=format&fit=crop", # Key 5
    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=600&auto=format&fit=crop", # Key 6
    "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=600&auto=format&fit=crop", # Key 7
    "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop", # Key 8
    "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=600&auto=format&fit=crop", # Key 9
    "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop", # Key 10
    "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&auto=format&fit=crop", # Key 11
    "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop", # Key 12
    "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=600&auto=format&fit=crop", # Key 13
    "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop", # Key 14
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=600&auto=format&fit=crop", # Key 15
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=600&auto=format&fit=crop", # Key 16
    "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop", # Key 17
    "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=600&auto=format&fit=crop", # Key 18
    "https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=80&w=600&auto=format&fit=crop", # Key 19
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop"  # Key 20
]

titles_10 = {
  "fr": ["Te connaître et t’aimer", "Cultiver ton indépendance", "Le mystère maîtrisé", "Communication claire et séduisante", "Le pouvoir du regard et du toucher", "Rituels matin/soir pour renforcer le lien", "L’art du compliment stratégique", "Maintenir la passion sexuelle", "Gérer les conflits avec classe", "Savoir dire non sans culpabilité", "Créer des surprises mémorables", "Tes limites = ton charme", "Le langage des petites attentions", "Entretenir ta vie sociale", "La confiance financière et émotionnelle", "Mise en valeur vestimentaire subtile", "Écouter activement et garder l’attention", "Réinventer les rendez-vous amoureux", "Le pardon qui protège la relation", "Devenir irremplaçable sans te perdre"],
  "en": ["Know and Love Yourself", "Cultivate Your Independence", "Mastered Mystery", "Clear and Seductive Communication", "The Power of Gaze and Touch", "Morning/Evening Rituals to Strengthen Connection", "The Art of Strategic Compliments", "Maintaining Sexual Passion", "Managing Conflicts with Class", "Knowing How to Say No Without Guilt", "Creating Memorable Surprises", "Your Boundaries = Your Charm", "The Language of Small Gestures", "Nurturing Your Social Life", "Financial and Emotional Confidence", "Subtle Style Enhancement", "Active Listening and Keeping Attention", "Reinventing Date Nights", "Forgiveness that Protects the Relationship", "Becoming Irreplaceable Without Losing Yourself"],
  "es": ["Conocerte y Amarte", "Cultivar tu Independencia", "El Misterio Dominado", "Comunicación Clara y Seductora", "El Poder de la Mirada y del Tacto", "Rituales Mañana/Noche para Reforzar el Vínculo", "El Arte del Cumplido Estratégico", "Mantener la Pasión Sexual", "Manejar Conflictos con Clase", "Saber Decir No sin Culpabilidad", "Crear Sorpresas Memorables", "Tus Límites = Tu Encanto", "El Lenguaje de los Pequeños Detalles", "Mantener tu Vida Social", "La Confianza Financiera y Emocional", "Realce Vestimentario Sutil", "Escuchar Activamente y Mantener la Atención", "Reinventar las Citas Románticas", "El Perdón que Protege la Relación", "Volverte Irremplazable sin Perderte"],
  "de": ["Dich Selbst Kennen und Lieben", "Kultiviere Deine Unabhängigkeit", "Geheimnis Vollendet", "Klare und Verlockende Kommunikation", "Die Macht des Blicks und der Berührung", "Morgen-/Abendrituale zur Stärkung der Bindung", "Die Kunst des Strategischen Kompliments", "Sexuelle Leidenschaft Bewahren", "Konflikte mit Stil Lösen", "Nein Sagen Ohne Schuldgefühle", "Unvergessliche Überraschungen Schaffen", "Deine Grenzen = Dein Charme", "Die Sprache der Kleinen Aufmerksamkeiten", "Dein Soziales Leben Pflegen", "Finanzielles und Emotionales Vertrauen", "Subtile Stilvolle Hervorhebung", "Aktives Zuhören und Aufmerksam Bleiben", "Dates Neu Erfinden", "Vergebung, Die die Beziehung Schützt", "Unersetzlich Werden Ohne Dich zu Verlieren"],
  "it": ["Conoscerti e Amarti", "Coltivare la Tua Indipendenza", "Il Mistero Padroneggiato", "Comunicazione Chiara e Seducente", "Il Potere dello Sguardo e del Tatto", "Rituali Mattina/Sera per Rinforzare il Legame", "L'Arte del Complimento Strategico", "Mantenere la Passione Sessuale", "Gestire i Conflitti con Classe", "Saper Dire No Senza Senso di Colpa", "Creare Sorprese Memorabili", "I Tuoi Limiti = Il Tuo Fascino", "Il Linguaggio delle Piccole Attenzioni", "Mantenere la Tua Vita Sociale", "La Fiducia Finanziaria ed Emozionale", "Valorizzazione dell'Abbigliamento Subdola", "Ascoltare Attivamente e Mantenere l'Attenzione", "Rinverdire gli Appuntamenti Romantici", "Il Perdono che Protegge la Relazione", "Diventare Insostituibile Senza Perderti"],
  "pt": ["Conhecer-te e Amar-te", "Cultivar a Tua Independência", "O Mistério Dominado", "Comunicação Clara e Sedutora", "O Poder do Olhar e do Toque", "Rituais Manhã/Noite para Reforçar a Ligação", "A Arte do Elogio Estratégico", "Manter a Paixão Sexual", "Gerir Conflitos com Classe", "Saber Dizer Não sem Culpabilidade", "Criar Surpresas Memoráveis", "Os Teus Limites = O Teu Charme", "O Linguagem das Pequenas Atenções", "Cultivar a Tua Vida Social", "A Confiança Financeira e Emocional", "Valorização do Estilo Subtil", "Escuta Ativa e Manter a Atenção", "Reinventar Encontros Românticos", "O Perdão que Protege a Relação", "Tornar-te Irsubstituível sem te Perderes"],
  "nl": ["Kennis en Zelfliefde", "Onafhankelijkheid Cultiveren", "Beheerst Mysterie", "Duidelijke en Verleidelijke Communicatie", "Kracht van Blik en Aanraking", "Dagelijkse Rituelen om de Band te Versterken", "Strategische Complimenten", "Seksuele Passie Behouden", "Conflictbeheersing met Klasse", "Nee Zeggen Zonder Schuldgevoel", "Gedenkwaardige Verrassingen", "Je Grenzen = Je Charme", "Kleine Attenties", "Sociaal Leven Koesteren", "Financiële & Emotionele Zekerheid", "Subtiele Kledingstijl", "Actief Luisteren en Aandacht Houden", "Dates Herontdekken", "Vergeving die de Relatie Beschermt", "Onvervangbaar Worden Zonder Je te Verliezen"],
  "ru": ["Познать и Полюбить Себя", "Развивать Независимость", "Мастерство Тайны", "Четкое и Соблазнительное Общение", "Сила Взгляда и Прикосновения", "Утренние и Вечерние Ритуалы", "Стратегический Комплимент", "Сохранять Сексуальную Страсть", "Управление Конфликтами с Классом", "Уметь Говорить «Нет» Без Вины", "Создание Незабываемых Сюрпризов", "Твои Границы = Твой Шарм", "Язык Мелочей и Внимания", "Поддерживать Социальную Жизнь", "Финансовая и Эмоциональная Уверенность", "Утонченный Стиль в Одежде", "Активное Слушание и Удержание Внимания", "Переосмысление Романтических Свиданий", "Прощение, Защищающее Отношения", "Стать Незаменимой, Не Теряя Себя"],
  "tr": ["Kendini Tanı ve Sev", "Bağımsızlığını Geliştir", "Gizemi Yönetmek", "Net ve Etkileyici İletişim", "Bakışın ve Dokunuşun Gücü", "İlişkiyi Güçlendiren Günlük Ritüeller", "Stratejik İltifat Sanatı", "Cinsel Tutkuyu Korumak", "Zarafetle Çatışma Yönetimi", "Suçluluk Duymadan Hayır Demek", "Unutulmaz Sürprizler Oluşturmak", "Sınırların = Çekiciliğin", "Küçük İlgi Dili", "Sosyal Yaşamı Korumak", "Finansal ve Duygusal Özgüven", "Zarif Giyim Tarzı", "Etkin Dinleme ve İlgiyi Canlı Tutmak", "Buluşmaları Yeniden Keşfetmek", "İlişkiyi Koruyan Bağışlama", "Kendini Kaybetmeden Vazgeçilmez Olmak"],
  "ar": ["أن تعرفي نفسكِ وتُحبيها", "تنمية استقلاليتكِ", "إتقان الغموض", "تواصل واضح وجذاب", "قوة النظرة واللمسة", "طقوس الصباح والمساء لتعزيز الرابط", "فن الإطراء الاستراتيجي", "الحفاظ على الشغف", "إدارة الخلافات برقي", "قول لا دون شعور بالذنب", "صنع مفاجآت لا تُنسى", "حُدودكِ = سحركِ", "لغة الاهتمامات الصغيرة", "الاهتمام بالحياة الاجتماعية", "الثقة المالية والعاطفية", "إبراز الأناقة بذكاء", "الاستماع الفعال وجذب الانتباه", "تجديد المواعيد الغرامية", "المغفرة التي تحمي العلاقة", "أن تصبحي لا تُعوضين دون أن تفقدي ذاتكِ"]
}

print("Titles for 10 languages parsed cleanly")
